/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcompanharRouteImport } from './routes/acompanhar'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CardapioRouteImport } from './routes/cardapio'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as EntregaRouteImport } from './routes/entrega'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as KinoRouteImport } from './routes/kino'
import { Route as OfertasRouteImport } from './routes/ofertas'
import { Route as ParceirosRouteImport } from './routes/parceiros'
import { Route as PedidoConfirmadoRouteImport } from './routes/pedido-confirmado'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PreferenciasRouteImport } from './routes/preferencias'
import { Route as ReservasRouteImport } from './routes/reservas'
import { Route as RestaurantesRouteImport } from './routes/restaurantes'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PratoDishIdRouteImport } from './routes/prato.$dishId'
import { Route as RestaurantesIdRouteImport } from './routes/restaurantes_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcompanharRoute = AcompanharRouteImport.update({
  id: '/acompanhar',
  path: '/acompanhar',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CardapioRoute = CardapioRouteImport.update({
  id: '/cardapio',
  path: '/cardapio',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregaRoute = EntregaRouteImport.update({
  id: '/entrega',
  path: '/entrega',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const KinoRoute = KinoRouteImport.update({
  id: '/kino',
  path: '/kino',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertasRoute = OfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceirosRoute = ParceirosRouteImport.update({
  id: '/parceiros',
  path: '/parceiros',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoConfirmadoRoute = PedidoConfirmadoRouteImport.update({
  id: '/pedido-confirmado',
  path: '/pedido-confirmado',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferenciasRoute = PreferenciasRouteImport.update({
  id: '/preferencias',
  path: '/preferencias',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservasRoute = ReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantesRoute = RestaurantesRouteImport.update({
  id: '/restaurantes',
  path: '/restaurantes',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PratoDishIdRoute = PratoDishIdRouteImport.update({
  id: '/prato/$dishId',
  path: '/prato/$dishId',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantesIdRoute = RestaurantesIdRouteImport.update({
  id: '/restaurantes_/$id',
  path: '/restaurantes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acompanhar': typeof AcompanharRoute
  '/ajuda': typeof AjudaRoute
  '/cadastro': typeof CadastroRoute
  '/cardapio': typeof CardapioRoute
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/entrar': typeof EntrarRoute
  '/entrega': typeof EntregaRoute
  '/favoritos': typeof FavoritosRoute
  '/kino': typeof KinoRoute
  '/ofertas': typeof OfertasRoute
  '/parceiros': typeof ParceirosRoute
  '/pedido-confirmado': typeof PedidoConfirmadoRoute
  '/perfil': typeof PerfilRoute
  '/preferencias': typeof PreferenciasRoute
  '/reservas': typeof ReservasRoute
  '/restaurantes': typeof RestaurantesRoute
  '/sobre': typeof SobreRoute
  '/prato/$dishId': typeof PratoDishIdRoute
  '/restaurantes/$id': typeof RestaurantesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acompanhar': typeof AcompanharRoute
  '/ajuda': typeof AjudaRoute
  '/cadastro': typeof CadastroRoute
  '/cardapio': typeof CardapioRoute
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/entrar': typeof EntrarRoute
  '/entrega': typeof EntregaRoute
  '/favoritos': typeof FavoritosRoute
  '/kino': typeof KinoRoute
  '/ofertas': typeof OfertasRoute
  '/parceiros': typeof ParceirosRoute
  '/pedido-confirmado': typeof PedidoConfirmadoRoute
  '/perfil': typeof PerfilRoute
  '/preferencias': typeof PreferenciasRoute
  '/reservas': typeof ReservasRoute
  '/restaurantes': typeof RestaurantesRoute
  '/sobre': typeof SobreRoute
  '/prato/$dishId': typeof PratoDishIdRoute
  '/restaurantes/$id': typeof RestaurantesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acompanhar': typeof AcompanharRoute
  '/ajuda': typeof AjudaRoute
  '/cadastro': typeof CadastroRoute
  '/cardapio': typeof CardapioRoute
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/entrar': typeof EntrarRoute
  '/entrega': typeof EntregaRoute
  '/favoritos': typeof FavoritosRoute
  '/kino': typeof KinoRoute
  '/ofertas': typeof OfertasRoute
  '/parceiros': typeof ParceirosRoute
  '/pedido-confirmado': typeof PedidoConfirmadoRoute
  '/perfil': typeof PerfilRoute
  '/preferencias': typeof PreferenciasRoute
  '/reservas': typeof ReservasRoute
  '/restaurantes': typeof RestaurantesRoute
  '/sobre': typeof SobreRoute
  '/prato/$dishId': typeof PratoDishIdRoute
  '/restaurantes_/$id': typeof RestaurantesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acompanhar'
    | '/ajuda'
    | '/cadastro'
    | '/cardapio'
    | '/checkout'
    | '/contacto'
    | '/entrar'
    | '/entrega'
    | '/favoritos'
    | '/kino'
    | '/ofertas'
    | '/parceiros'
    | '/pedido-confirmado'
    | '/perfil'
    | '/preferencias'
    | '/reservas'
    | '/restaurantes'
    | '/sobre'
    | '/prato/$dishId'
    | '/restaurantes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acompanhar'
    | '/ajuda'
    | '/cadastro'
    | '/cardapio'
    | '/checkout'
    | '/contacto'
    | '/entrar'
    | '/entrega'
    | '/favoritos'
    | '/kino'
    | '/ofertas'
    | '/parceiros'
    | '/pedido-confirmado'
    | '/perfil'
    | '/preferencias'
    | '/reservas'
    | '/restaurantes'
    | '/sobre'
    | '/prato/$dishId'
    | '/restaurantes/$id'
  id:
    | '__root__'
    | '/'
    | '/acompanhar'
    | '/ajuda'
    | '/cadastro'
    | '/cardapio'
    | '/checkout'
    | '/contacto'
    | '/entrar'
    | '/entrega'
    | '/favoritos'
    | '/kino'
    | '/ofertas'
    | '/parceiros'
    | '/pedido-confirmado'
    | '/perfil'
    | '/preferencias'
    | '/reservas'
    | '/restaurantes'
    | '/sobre'
    | '/prato/$dishId'
    | '/restaurantes_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcompanharRoute: typeof AcompanharRoute
  AjudaRoute: typeof AjudaRoute
  CadastroRoute: typeof CadastroRoute
  CardapioRoute: typeof CardapioRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactoRoute: typeof ContactoRoute
  EntrarRoute: typeof EntrarRoute
  EntregaRoute: typeof EntregaRoute
  FavoritosRoute: typeof FavoritosRoute
  KinoRoute: typeof KinoRoute
  OfertasRoute: typeof OfertasRoute
  ParceirosRoute: typeof ParceirosRoute
  PedidoConfirmadoRoute: typeof PedidoConfirmadoRoute
  PerfilRoute: typeof PerfilRoute
  PreferenciasRoute: typeof PreferenciasRoute
  ReservasRoute: typeof ReservasRoute
  RestaurantesRoute: typeof RestaurantesRoute
  SobreRoute: typeof SobreRoute
  PratoDishIdRoute: typeof PratoDishIdRoute
  RestaurantesIdRoute: typeof RestaurantesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acompanhar': {
      id: '/acompanhar'
      path: '/acompanhar'
      fullPath: '/acompanhar'
      preLoaderRoute: typeof AcompanharRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cardapio': {
      id: '/cardapio'
      path: '/cardapio'
      fullPath: '/cardapio'
      preLoaderRoute: typeof CardapioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrega': {
      id: '/entrega'
      path: '/entrega'
      fullPath: '/entrega'
      preLoaderRoute: typeof EntregaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kino': {
      id: '/kino'
      path: '/kino'
      fullPath: '/kino'
      preLoaderRoute: typeof KinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertas': {
      id: '/ofertas'
      path: '/ofertas'
      fullPath: '/ofertas'
      preLoaderRoute: typeof OfertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceiros': {
      id: '/parceiros'
      path: '/parceiros'
      fullPath: '/parceiros'
      preLoaderRoute: typeof ParceirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido-confirmado': {
      id: '/pedido-confirmado'
      path: '/pedido-confirmado'
      fullPath: '/pedido-confirmado'
      preLoaderRoute: typeof PedidoConfirmadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferencias': {
      id: '/preferencias'
      path: '/preferencias'
      fullPath: '/preferencias'
      preLoaderRoute: typeof PreferenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservas': {
      id: '/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof ReservasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurantes': {
      id: '/restaurantes'
      path: '/restaurantes'
      fullPath: '/restaurantes'
      preLoaderRoute: typeof RestaurantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prato/$dishId': {
      id: '/prato/$dishId'
      path: '/prato/$dishId'
      fullPath: '/prato/$dishId'
      preLoaderRoute: typeof PratoDishIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurantes_/$id': {
      id: '/restaurantes_/$id'
      path: '/restaurantes/$id'
      fullPath: '/restaurantes/$id'
      preLoaderRoute: typeof RestaurantesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcompanharRoute: AcompanharRoute,
  AjudaRoute: AjudaRoute,
  CadastroRoute: CadastroRoute,
  CardapioRoute: CardapioRoute,
  CheckoutRoute: CheckoutRoute,
  ContactoRoute: ContactoRoute,
  EntrarRoute: EntrarRoute,
  EntregaRoute: EntregaRoute,
  FavoritosRoute: FavoritosRoute,
  KinoRoute: KinoRoute,
  OfertasRoute: OfertasRoute,
  ParceirosRoute: ParceirosRoute,
  PedidoConfirmadoRoute: PedidoConfirmadoRoute,
  PerfilRoute: PerfilRoute,
  PreferenciasRoute: PreferenciasRoute,
  ReservasRoute: ReservasRoute,
  RestaurantesRoute: RestaurantesRoute,
  SobreRoute: SobreRoute,
  PratoDishIdRoute: PratoDishIdRoute,
  RestaurantesIdRoute: RestaurantesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
