/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CardapioRouteImport } from './routes/cardapio'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as EntregaRouteImport } from './routes/entrega'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as KinoRouteImport } from './routes/kino'
import { Route as OfertasRouteImport } from './routes/ofertas'
import { Route as ParceirosRouteImport } from './routes/parceiros'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PreferenciasRouteImport } from './routes/preferencias'
import { Route as ReservasRouteImport } from './routes/reservas'
import { Route as RestaurantesRouteImport } from './routes/restaurantes'
import { Route as SistemaRouteImport } from './routes/sistema'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAvaliacoesRouteImport } from './routes/admin.avaliacoes'
import { Route as AdminCardapioRouteImport } from './routes/admin.cardapio'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminEstatisticasRouteImport } from './routes/admin.estatisticas'
import { Route as AdminMesasRouteImport } from './routes/admin.mesas'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminPerfilRouteImport } from './routes/admin.perfil'
import { Route as AdminPromocoesRouteImport } from './routes/admin.promocoes'
import { Route as AdminReservasRouteImport } from './routes/admin.reservas'
import { Route as AdminStoriesRouteImport } from './routes/admin.stories'
import { Route as AdminSubscricaoRouteImport } from './routes/admin.subscricao'
import { Route as AdminSuporteRouteImport } from './routes/admin.suporte'
import { Route as AdminCardapioPdfRouteImport } from './routes/admin_.cardapio-pdf'
import { Route as AdminEntrarRouteImport } from './routes/admin_.entrar'
import { Route as MenuRestaurantIdRouteImport } from './routes/menu.$restaurantId'
import { Route as PratoDishIdRouteImport } from './routes/prato.$dishId'
import { Route as PratosDishNameRouteImport } from './routes/pratos.$dishName'
import { Route as RestaurantesIdRouteImport } from './routes/restaurantes_.$id'
import { Route as SistemaIndexRouteImport } from './routes/sistema.index'
import { Route as SistemaFrotaRouteImport } from './routes/sistema.frota'
import { Route as SistemaOperacaoRouteImport } from './routes/sistema.operacao'
import { Route as SistemaParceirosRouteImport } from './routes/sistema.parceiros'
import { Route as SistemaPromocoesRouteImport } from './routes/sistema.promocoes'
import { Route as SistemaRestaurantesRouteImport } from './routes/sistema.restaurantes'
import { Route as SistemaSubscricoesRouteImport } from './routes/sistema.subscricoes'
import { Route as SistemaSuporteRouteImport } from './routes/sistema.suporte'
import { Route as SistemaEntrarRouteImport } from './routes/sistema_.entrar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CardapioRoute = CardapioRouteImport.update({
  id: '/cardapio',
  path: '/cardapio',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregaRoute = EntregaRouteImport.update({
  id: '/entrega',
  path: '/entrega',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const KinoRoute = KinoRouteImport.update({
  id: '/kino',
  path: '/kino',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertasRoute = OfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceirosRoute = ParceirosRouteImport.update({
  id: '/parceiros',
  path: '/parceiros',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferenciasRoute = PreferenciasRouteImport.update({
  id: '/preferencias',
  path: '/preferencias',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservasRoute = ReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantesRoute = RestaurantesRouteImport.update({
  id: '/restaurantes',
  path: '/restaurantes',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemaRoute = SistemaRouteImport.update({
  id: '/sistema',
  path: '/sistema',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAvaliacoesRoute = AdminAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCardapioRoute = AdminCardapioRouteImport.update({
  id: '/cardapio',
  path: '/cardapio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEstatisticasRoute = AdminEstatisticasRouteImport.update({
  id: '/estatisticas',
  path: '/estatisticas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMesasRoute = AdminMesasRouteImport.update({
  id: '/mesas',
  path: '/mesas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPerfilRoute = AdminPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromocoesRoute = AdminPromocoesRouteImport.update({
  id: '/promocoes',
  path: '/promocoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReservasRoute = AdminReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStoriesRoute = AdminStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscricaoRoute = AdminSubscricaoRouteImport.update({
  id: '/subscricao',
  path: '/subscricao',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuporteRoute = AdminSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCardapioPdfRoute = AdminCardapioPdfRouteImport.update({
  id: '/admin_/cardapio-pdf',
  path: '/admin/cardapio-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEntrarRoute = AdminEntrarRouteImport.update({
  id: '/admin_/entrar',
  path: '/admin/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRestaurantIdRoute = MenuRestaurantIdRouteImport.update({
  id: '/menu/$restaurantId',
  path: '/menu/$restaurantId',
  getParentRoute: () => rootRouteImport,
} as any)
const PratoDishIdRoute = PratoDishIdRouteImport.update({
  id: '/prato/$dishId',
  path: '/prato/$dishId',
  getParentRoute: () => rootRouteImport,
} as any)
const PratosDishNameRoute = PratosDishNameRouteImport.update({
  id: '/pratos/$dishName',
  path: '/pratos/$dishName',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantesIdRoute = RestaurantesIdRouteImport.update({
  id: '/restaurantes_/$id',
  path: '/restaurantes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemaIndexRoute = SistemaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SistemaRoute,
} as any)
const SistemaFrotaRoute = SistemaFrotaRouteImport.update({
  id: '/frota',
  path: '/frota',
  getParentRoute: () => SistemaRoute,
} as any)
const SistemaOperacaoRoute = SistemaOperacaoRouteImport.update({
  id: '/operacao',
  path: '/operacao',
  getParentRoute: () => SistemaRoute,
} as any)
const SistemaParceirosRoute = SistemaParceirosRouteImport.update({
  id: '/parceiros',
  path: '/parceiros',
  getParentRoute: () => SistemaRoute,
} as any)
const SistemaPromocoesRoute = SistemaPromocoesRouteImport.update({
  id: '/promocoes',
  path: '/promocoes',
  getParentRoute: () => SistemaRoute,
} as any)
const SistemaRestaurantesRoute = SistemaRestaurantesRouteImport.update({
  id: '/restaurantes',
  path: '/restaurantes',
  getParentRoute: () => SistemaRoute,
} as any)
const SistemaSubscricoesRoute = SistemaSubscricoesRouteImport.update({
  id: '/subscricoes',
  path: '/subscricoes',
  getParentRoute: () => SistemaRoute,
} as any)
const SistemaSuporteRoute = SistemaSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => SistemaRoute,
} as any)
const SistemaEntrarRoute = SistemaEntrarRouteImport.update({
  id: '/sistema_/entrar',
  path: '/sistema/entrar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ajuda': typeof AjudaRoute
  '/cadastro': typeof CadastroRoute
  '/cardapio': typeof CardapioRoute
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/entrar': typeof EntrarRoute
  '/entrega': typeof EntregaRoute
  '/favoritos': typeof FavoritosRoute
  '/kino': typeof KinoRoute
  '/ofertas': typeof OfertasRoute
  '/parceiros': typeof ParceirosRoute
  '/perfil': typeof PerfilRoute
  '/preferencias': typeof PreferenciasRoute
  '/reservas': typeof ReservasRoute
  '/restaurantes': typeof RestaurantesRoute
  '/sistema': typeof SistemaRouteWithChildren
  '/sobre': typeof SobreRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/cardapio': typeof AdminCardapioRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/estatisticas': typeof AdminEstatisticasRoute
  '/admin/mesas': typeof AdminMesasRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/perfil': typeof AdminPerfilRoute
  '/admin/promocoes': typeof AdminPromocoesRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/admin/stories': typeof AdminStoriesRoute
  '/admin/subscricao': typeof AdminSubscricaoRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/cardapio-pdf': typeof AdminCardapioPdfRoute
  '/admin/entrar': typeof AdminEntrarRoute
  '/menu/$restaurantId': typeof MenuRestaurantIdRoute
  '/prato/$dishId': typeof PratoDishIdRoute
  '/pratos/$dishName': typeof PratosDishNameRoute
  '/restaurantes/$id': typeof RestaurantesIdRoute
  '/sistema/frota': typeof SistemaFrotaRoute
  '/sistema/operacao': typeof SistemaOperacaoRoute
  '/sistema/parceiros': typeof SistemaParceirosRoute
  '/sistema/promocoes': typeof SistemaPromocoesRoute
  '/sistema/restaurantes': typeof SistemaRestaurantesRoute
  '/sistema/subscricoes': typeof SistemaSubscricoesRoute
  '/sistema/suporte': typeof SistemaSuporteRoute
  '/sistema/entrar': typeof SistemaEntrarRoute
  '/admin/': typeof AdminIndexRoute
  '/sistema/': typeof SistemaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/cadastro': typeof CadastroRoute
  '/cardapio': typeof CardapioRoute
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/entrar': typeof EntrarRoute
  '/entrega': typeof EntregaRoute
  '/favoritos': typeof FavoritosRoute
  '/kino': typeof KinoRoute
  '/ofertas': typeof OfertasRoute
  '/parceiros': typeof ParceirosRoute
  '/perfil': typeof PerfilRoute
  '/preferencias': typeof PreferenciasRoute
  '/reservas': typeof ReservasRoute
  '/restaurantes': typeof RestaurantesRoute
  '/sobre': typeof SobreRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/cardapio': typeof AdminCardapioRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/estatisticas': typeof AdminEstatisticasRoute
  '/admin/mesas': typeof AdminMesasRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/perfil': typeof AdminPerfilRoute
  '/admin/promocoes': typeof AdminPromocoesRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/admin/stories': typeof AdminStoriesRoute
  '/admin/subscricao': typeof AdminSubscricaoRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/cardapio-pdf': typeof AdminCardapioPdfRoute
  '/admin/entrar': typeof AdminEntrarRoute
  '/menu/$restaurantId': typeof MenuRestaurantIdRoute
  '/prato/$dishId': typeof PratoDishIdRoute
  '/pratos/$dishName': typeof PratosDishNameRoute
  '/restaurantes/$id': typeof RestaurantesIdRoute
  '/sistema/frota': typeof SistemaFrotaRoute
  '/sistema/operacao': typeof SistemaOperacaoRoute
  '/sistema/parceiros': typeof SistemaParceirosRoute
  '/sistema/promocoes': typeof SistemaPromocoesRoute
  '/sistema/restaurantes': typeof SistemaRestaurantesRoute
  '/sistema/subscricoes': typeof SistemaSubscricoesRoute
  '/sistema/suporte': typeof SistemaSuporteRoute
  '/sistema/entrar': typeof SistemaEntrarRoute
  '/admin': typeof AdminIndexRoute
  '/sistema': typeof SistemaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ajuda': typeof AjudaRoute
  '/cadastro': typeof CadastroRoute
  '/cardapio': typeof CardapioRoute
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/entrar': typeof EntrarRoute
  '/entrega': typeof EntregaRoute
  '/favoritos': typeof FavoritosRoute
  '/kino': typeof KinoRoute
  '/ofertas': typeof OfertasRoute
  '/parceiros': typeof ParceirosRoute
  '/perfil': typeof PerfilRoute
  '/preferencias': typeof PreferenciasRoute
  '/reservas': typeof ReservasRoute
  '/restaurantes': typeof RestaurantesRoute
  '/sistema': typeof SistemaRouteWithChildren
  '/sobre': typeof SobreRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/cardapio': typeof AdminCardapioRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/estatisticas': typeof AdminEstatisticasRoute
  '/admin/mesas': typeof AdminMesasRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/perfil': typeof AdminPerfilRoute
  '/admin/promocoes': typeof AdminPromocoesRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/admin/stories': typeof AdminStoriesRoute
  '/admin/subscricao': typeof AdminSubscricaoRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin_/cardapio-pdf': typeof AdminCardapioPdfRoute
  '/admin_/entrar': typeof AdminEntrarRoute
  '/menu/$restaurantId': typeof MenuRestaurantIdRoute
  '/prato/$dishId': typeof PratoDishIdRoute
  '/pratos/$dishName': typeof PratosDishNameRoute
  '/restaurantes_/$id': typeof RestaurantesIdRoute
  '/sistema/frota': typeof SistemaFrotaRoute
  '/sistema/operacao': typeof SistemaOperacaoRoute
  '/sistema/parceiros': typeof SistemaParceirosRoute
  '/sistema/promocoes': typeof SistemaPromocoesRoute
  '/sistema/restaurantes': typeof SistemaRestaurantesRoute
  '/sistema/subscricoes': typeof SistemaSubscricoesRoute
  '/sistema/suporte': typeof SistemaSuporteRoute
  '/sistema_/entrar': typeof SistemaEntrarRoute
  '/admin/': typeof AdminIndexRoute
  '/sistema/': typeof SistemaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ajuda'
    | '/cadastro'
    | '/cardapio'
    | '/checkout'
    | '/contacto'
    | '/entrar'
    | '/entrega'
    | '/favoritos'
    | '/kino'
    | '/ofertas'
    | '/parceiros'
    | '/perfil'
    | '/preferencias'
    | '/reservas'
    | '/restaurantes'
    | '/sistema'
    | '/sobre'
    | '/admin/avaliacoes'
    | '/admin/cardapio'
    | '/admin/clientes'
    | '/admin/estatisticas'
    | '/admin/mesas'
    | '/admin/pedidos'
    | '/admin/perfil'
    | '/admin/promocoes'
    | '/admin/reservas'
    | '/admin/stories'
    | '/admin/subscricao'
    | '/admin/suporte'
    | '/admin/cardapio-pdf'
    | '/admin/entrar'
    | '/menu/$restaurantId'
    | '/prato/$dishId'
    | '/pratos/$dishName'
    | '/restaurantes/$id'
    | '/sistema/frota'
    | '/sistema/operacao'
    | '/sistema/parceiros'
    | '/sistema/promocoes'
    | '/sistema/restaurantes'
    | '/sistema/subscricoes'
    | '/sistema/suporte'
    | '/sistema/entrar'
    | '/admin/'
    | '/sistema/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajuda'
    | '/cadastro'
    | '/cardapio'
    | '/checkout'
    | '/contacto'
    | '/entrar'
    | '/entrega'
    | '/favoritos'
    | '/kino'
    | '/ofertas'
    | '/parceiros'
    | '/perfil'
    | '/preferencias'
    | '/reservas'
    | '/restaurantes'
    | '/sobre'
    | '/admin/avaliacoes'
    | '/admin/cardapio'
    | '/admin/clientes'
    | '/admin/estatisticas'
    | '/admin/mesas'
    | '/admin/pedidos'
    | '/admin/perfil'
    | '/admin/promocoes'
    | '/admin/reservas'
    | '/admin/stories'
    | '/admin/subscricao'
    | '/admin/suporte'
    | '/admin/cardapio-pdf'
    | '/admin/entrar'
    | '/menu/$restaurantId'
    | '/prato/$dishId'
    | '/pratos/$dishName'
    | '/restaurantes/$id'
    | '/sistema/frota'
    | '/sistema/operacao'
    | '/sistema/parceiros'
    | '/sistema/promocoes'
    | '/sistema/restaurantes'
    | '/sistema/subscricoes'
    | '/sistema/suporte'
    | '/sistema/entrar'
    | '/admin'
    | '/sistema'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ajuda'
    | '/cadastro'
    | '/cardapio'
    | '/checkout'
    | '/contacto'
    | '/entrar'
    | '/entrega'
    | '/favoritos'
    | '/kino'
    | '/ofertas'
    | '/parceiros'
    | '/perfil'
    | '/preferencias'
    | '/reservas'
    | '/restaurantes'
    | '/sistema'
    | '/sobre'
    | '/admin/avaliacoes'
    | '/admin/cardapio'
    | '/admin/clientes'
    | '/admin/estatisticas'
    | '/admin/mesas'
    | '/admin/pedidos'
    | '/admin/perfil'
    | '/admin/promocoes'
    | '/admin/reservas'
    | '/admin/stories'
    | '/admin/subscricao'
    | '/admin/suporte'
    | '/admin_/cardapio-pdf'
    | '/admin_/entrar'
    | '/menu/$restaurantId'
    | '/prato/$dishId'
    | '/pratos/$dishName'
    | '/restaurantes_/$id'
    | '/sistema/frota'
    | '/sistema/operacao'
    | '/sistema/parceiros'
    | '/sistema/promocoes'
    | '/sistema/restaurantes'
    | '/sistema/subscricoes'
    | '/sistema/suporte'
    | '/sistema_/entrar'
    | '/admin/'
    | '/sistema/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AjudaRoute: typeof AjudaRoute
  CadastroRoute: typeof CadastroRoute
  CardapioRoute: typeof CardapioRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactoRoute: typeof ContactoRoute
  EntrarRoute: typeof EntrarRoute
  EntregaRoute: typeof EntregaRoute
  FavoritosRoute: typeof FavoritosRoute
  KinoRoute: typeof KinoRoute
  OfertasRoute: typeof OfertasRoute
  ParceirosRoute: typeof ParceirosRoute
  PerfilRoute: typeof PerfilRoute
  PreferenciasRoute: typeof PreferenciasRoute
  ReservasRoute: typeof ReservasRoute
  RestaurantesRoute: typeof RestaurantesRoute
  SistemaRoute: typeof SistemaRouteWithChildren
  SobreRoute: typeof SobreRoute
  AdminCardapioPdfRoute: typeof AdminCardapioPdfRoute
  AdminEntrarRoute: typeof AdminEntrarRoute
  MenuRestaurantIdRoute: typeof MenuRestaurantIdRoute
  PratoDishIdRoute: typeof PratoDishIdRoute
  PratosDishNameRoute: typeof PratosDishNameRoute
  RestaurantesIdRoute: typeof RestaurantesIdRoute
  SistemaEntrarRoute: typeof SistemaEntrarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cardapio': {
      id: '/cardapio'
      path: '/cardapio'
      fullPath: '/cardapio'
      preLoaderRoute: typeof CardapioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrega': {
      id: '/entrega'
      path: '/entrega'
      fullPath: '/entrega'
      preLoaderRoute: typeof EntregaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kino': {
      id: '/kino'
      path: '/kino'
      fullPath: '/kino'
      preLoaderRoute: typeof KinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertas': {
      id: '/ofertas'
      path: '/ofertas'
      fullPath: '/ofertas'
      preLoaderRoute: typeof OfertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceiros': {
      id: '/parceiros'
      path: '/parceiros'
      fullPath: '/parceiros'
      preLoaderRoute: typeof ParceirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferencias': {
      id: '/preferencias'
      path: '/preferencias'
      fullPath: '/preferencias'
      preLoaderRoute: typeof PreferenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservas': {
      id: '/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof ReservasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurantes': {
      id: '/restaurantes'
      path: '/restaurantes'
      fullPath: '/restaurantes'
      preLoaderRoute: typeof RestaurantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistema': {
      id: '/sistema'
      path: '/sistema'
      fullPath: '/sistema'
      preLoaderRoute: typeof SistemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/avaliacoes': {
      id: '/admin/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/admin/avaliacoes'
      preLoaderRoute: typeof AdminAvaliacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cardapio': {
      id: '/admin/cardapio'
      path: '/cardapio'
      fullPath: '/admin/cardapio'
      preLoaderRoute: typeof AdminCardapioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estatisticas': {
      id: '/admin/estatisticas'
      path: '/estatisticas'
      fullPath: '/admin/estatisticas'
      preLoaderRoute: typeof AdminEstatisticasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mesas': {
      id: '/admin/mesas'
      path: '/mesas'
      fullPath: '/admin/mesas'
      preLoaderRoute: typeof AdminMesasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/perfil': {
      id: '/admin/perfil'
      path: '/perfil'
      fullPath: '/admin/perfil'
      preLoaderRoute: typeof AdminPerfilRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promocoes': {
      id: '/admin/promocoes'
      path: '/promocoes'
      fullPath: '/admin/promocoes'
      preLoaderRoute: typeof AdminPromocoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reservas': {
      id: '/admin/reservas'
      path: '/reservas'
      fullPath: '/admin/reservas'
      preLoaderRoute: typeof AdminReservasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stories': {
      id: '/admin/stories'
      path: '/stories'
      fullPath: '/admin/stories'
      preLoaderRoute: typeof AdminStoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscricao': {
      id: '/admin/subscricao'
      path: '/subscricao'
      fullPath: '/admin/subscricao'
      preLoaderRoute: typeof AdminSubscricaoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suporte': {
      id: '/admin/suporte'
      path: '/suporte'
      fullPath: '/admin/suporte'
      preLoaderRoute: typeof AdminSuporteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin_/cardapio-pdf': {
      id: '/admin_/cardapio-pdf'
      path: '/admin/cardapio-pdf'
      fullPath: '/admin/cardapio-pdf'
      preLoaderRoute: typeof AdminCardapioPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/entrar': {
      id: '/admin_/entrar'
      path: '/admin/entrar'
      fullPath: '/admin/entrar'
      preLoaderRoute: typeof AdminEntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/$restaurantId': {
      id: '/menu/$restaurantId'
      path: '/menu/$restaurantId'
      fullPath: '/menu/$restaurantId'
      preLoaderRoute: typeof MenuRestaurantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prato/$dishId': {
      id: '/prato/$dishId'
      path: '/prato/$dishId'
      fullPath: '/prato/$dishId'
      preLoaderRoute: typeof PratoDishIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pratos/$dishName': {
      id: '/pratos/$dishName'
      path: '/pratos/$dishName'
      fullPath: '/pratos/$dishName'
      preLoaderRoute: typeof PratosDishNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurantes_/$id': {
      id: '/restaurantes_/$id'
      path: '/restaurantes/$id'
      fullPath: '/restaurantes/$id'
      preLoaderRoute: typeof RestaurantesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistema/': {
      id: '/sistema/'
      path: '/'
      fullPath: '/sistema/'
      preLoaderRoute: typeof SistemaIndexRouteImport
      parentRoute: typeof SistemaRoute
    }
    '/sistema/frota': {
      id: '/sistema/frota'
      path: '/frota'
      fullPath: '/sistema/frota'
      preLoaderRoute: typeof SistemaFrotaRouteImport
      parentRoute: typeof SistemaRoute
    }
    '/sistema/operacao': {
      id: '/sistema/operacao'
      path: '/operacao'
      fullPath: '/sistema/operacao'
      preLoaderRoute: typeof SistemaOperacaoRouteImport
      parentRoute: typeof SistemaRoute
    }
    '/sistema/parceiros': {
      id: '/sistema/parceiros'
      path: '/parceiros'
      fullPath: '/sistema/parceiros'
      preLoaderRoute: typeof SistemaParceirosRouteImport
      parentRoute: typeof SistemaRoute
    }
    '/sistema/promocoes': {
      id: '/sistema/promocoes'
      path: '/promocoes'
      fullPath: '/sistema/promocoes'
      preLoaderRoute: typeof SistemaPromocoesRouteImport
      parentRoute: typeof SistemaRoute
    }
    '/sistema/restaurantes': {
      id: '/sistema/restaurantes'
      path: '/restaurantes'
      fullPath: '/sistema/restaurantes'
      preLoaderRoute: typeof SistemaRestaurantesRouteImport
      parentRoute: typeof SistemaRoute
    }
    '/sistema/subscricoes': {
      id: '/sistema/subscricoes'
      path: '/subscricoes'
      fullPath: '/sistema/subscricoes'
      preLoaderRoute: typeof SistemaSubscricoesRouteImport
      parentRoute: typeof SistemaRoute
    }
    '/sistema/suporte': {
      id: '/sistema/suporte'
      path: '/suporte'
      fullPath: '/sistema/suporte'
      preLoaderRoute: typeof SistemaSuporteRouteImport
      parentRoute: typeof SistemaRoute
    }
    '/sistema_/entrar': {
      id: '/sistema_/entrar'
      path: '/sistema/entrar'
      fullPath: '/sistema/entrar'
      preLoaderRoute: typeof SistemaEntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAvaliacoesRoute: typeof AdminAvaliacoesRoute
  AdminCardapioRoute: typeof AdminCardapioRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminEstatisticasRoute: typeof AdminEstatisticasRoute
  AdminMesasRoute: typeof AdminMesasRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminPerfilRoute: typeof AdminPerfilRoute
  AdminPromocoesRoute: typeof AdminPromocoesRoute
  AdminReservasRoute: typeof AdminReservasRoute
  AdminStoriesRoute: typeof AdminStoriesRoute
  AdminSubscricaoRoute: typeof AdminSubscricaoRoute
  AdminSuporteRoute: typeof AdminSuporteRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAvaliacoesRoute: AdminAvaliacoesRoute,
  AdminCardapioRoute: AdminCardapioRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminEstatisticasRoute: AdminEstatisticasRoute,
  AdminMesasRoute: AdminMesasRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminPerfilRoute: AdminPerfilRoute,
  AdminPromocoesRoute: AdminPromocoesRoute,
  AdminReservasRoute: AdminReservasRoute,
  AdminStoriesRoute: AdminStoriesRoute,
  AdminSubscricaoRoute: AdminSubscricaoRoute,
  AdminSuporteRoute: AdminSuporteRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SistemaRouteChildren {
  SistemaFrotaRoute: typeof SistemaFrotaRoute
  SistemaOperacaoRoute: typeof SistemaOperacaoRoute
  SistemaParceirosRoute: typeof SistemaParceirosRoute
  SistemaPromocoesRoute: typeof SistemaPromocoesRoute
  SistemaRestaurantesRoute: typeof SistemaRestaurantesRoute
  SistemaSubscricoesRoute: typeof SistemaSubscricoesRoute
  SistemaSuporteRoute: typeof SistemaSuporteRoute
  SistemaIndexRoute: typeof SistemaIndexRoute
}

const SistemaRouteChildren: SistemaRouteChildren = {
  SistemaFrotaRoute: SistemaFrotaRoute,
  SistemaOperacaoRoute: SistemaOperacaoRoute,
  SistemaParceirosRoute: SistemaParceirosRoute,
  SistemaPromocoesRoute: SistemaPromocoesRoute,
  SistemaRestaurantesRoute: SistemaRestaurantesRoute,
  SistemaSubscricoesRoute: SistemaSubscricoesRoute,
  SistemaSuporteRoute: SistemaSuporteRoute,
  SistemaIndexRoute: SistemaIndexRoute,
}

const SistemaRouteWithChildren =
  SistemaRoute._addFileChildren(SistemaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AjudaRoute: AjudaRoute,
  CadastroRoute: CadastroRoute,
  CardapioRoute: CardapioRoute,
  CheckoutRoute: CheckoutRoute,
  ContactoRoute: ContactoRoute,
  EntrarRoute: EntrarRoute,
  EntregaRoute: EntregaRoute,
  FavoritosRoute: FavoritosRoute,
  KinoRoute: KinoRoute,
  OfertasRoute: OfertasRoute,
  ParceirosRoute: ParceirosRoute,
  PerfilRoute: PerfilRoute,
  PreferenciasRoute: PreferenciasRoute,
  ReservasRoute: ReservasRoute,
  RestaurantesRoute: RestaurantesRoute,
  SistemaRoute: SistemaRouteWithChildren,
  SobreRoute: SobreRoute,
  AdminCardapioPdfRoute: AdminCardapioPdfRoute,
  AdminEntrarRoute: AdminEntrarRoute,
  MenuRestaurantIdRoute: MenuRestaurantIdRoute,
  PratoDishIdRoute: PratoDishIdRoute,
  PratosDishNameRoute: PratosDishNameRoute,
  RestaurantesIdRoute: RestaurantesIdRoute,
  SistemaEntrarRoute: SistemaEntrarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
