/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CardapioRouteImport } from './routes/cardapio'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as EntregaRouteImport } from './routes/entrega'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as KinoRouteImport } from './routes/kino'
import { Route as OfertasRouteImport } from './routes/ofertas'
import { Route as ParceirosRouteImport } from './routes/parceiros'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PreferenciasRouteImport } from './routes/preferencias'
import { Route as ReservasRouteImport } from './routes/reservas'
import { Route as RestaurantesRouteImport } from './routes/restaurantes'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAvaliacoesRouteImport } from './routes/admin.avaliacoes'
import { Route as AdminCardapioRouteImport } from './routes/admin.cardapio'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminPerfilRouteImport } from './routes/admin.perfil'
import { Route as AdminReservasRouteImport } from './routes/admin.reservas'
import { Route as AdminEntrarRouteImport } from './routes/admin_.entrar'
import { Route as PratoDishIdRouteImport } from './routes/prato.$dishId'
import { Route as RestaurantesIdRouteImport } from './routes/restaurantes_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CardapioRoute = CardapioRouteImport.update({
  id: '/cardapio',
  path: '/cardapio',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregaRoute = EntregaRouteImport.update({
  id: '/entrega',
  path: '/entrega',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const KinoRoute = KinoRouteImport.update({
  id: '/kino',
  path: '/kino',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertasRoute = OfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceirosRoute = ParceirosRouteImport.update({
  id: '/parceiros',
  path: '/parceiros',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferenciasRoute = PreferenciasRouteImport.update({
  id: '/preferencias',
  path: '/preferencias',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservasRoute = ReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantesRoute = RestaurantesRouteImport.update({
  id: '/restaurantes',
  path: '/restaurantes',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAvaliacoesRoute = AdminAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCardapioRoute = AdminCardapioRouteImport.update({
  id: '/cardapio',
  path: '/cardapio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPerfilRoute = AdminPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReservasRoute = AdminReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEntrarRoute = AdminEntrarRouteImport.update({
  id: '/admin_/entrar',
  path: '/admin/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const PratoDishIdRoute = PratoDishIdRouteImport.update({
  id: '/prato/$dishId',
  path: '/prato/$dishId',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantesIdRoute = RestaurantesIdRouteImport.update({
  id: '/restaurantes_/$id',
  path: '/restaurantes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ajuda': typeof AjudaRoute
  '/cadastro': typeof CadastroRoute
  '/cardapio': typeof CardapioRoute
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/entrar': typeof EntrarRoute
  '/entrega': typeof EntregaRoute
  '/favoritos': typeof FavoritosRoute
  '/kino': typeof KinoRoute
  '/ofertas': typeof OfertasRoute
  '/parceiros': typeof ParceirosRoute
  '/perfil': typeof PerfilRoute
  '/preferencias': typeof PreferenciasRoute
  '/reservas': typeof ReservasRoute
  '/restaurantes': typeof RestaurantesRoute
  '/sobre': typeof SobreRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/cardapio': typeof AdminCardapioRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/perfil': typeof AdminPerfilRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/admin/entrar': typeof AdminEntrarRoute
  '/prato/$dishId': typeof PratoDishIdRoute
  '/restaurantes/$id': typeof RestaurantesIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/cadastro': typeof CadastroRoute
  '/cardapio': typeof CardapioRoute
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/entrar': typeof EntrarRoute
  '/entrega': typeof EntregaRoute
  '/favoritos': typeof FavoritosRoute
  '/kino': typeof KinoRoute
  '/ofertas': typeof OfertasRoute
  '/parceiros': typeof ParceirosRoute
  '/perfil': typeof PerfilRoute
  '/preferencias': typeof PreferenciasRoute
  '/reservas': typeof ReservasRoute
  '/restaurantes': typeof RestaurantesRoute
  '/sobre': typeof SobreRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/cardapio': typeof AdminCardapioRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/perfil': typeof AdminPerfilRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/admin/entrar': typeof AdminEntrarRoute
  '/prato/$dishId': typeof PratoDishIdRoute
  '/restaurantes/$id': typeof RestaurantesIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ajuda': typeof AjudaRoute
  '/cadastro': typeof CadastroRoute
  '/cardapio': typeof CardapioRoute
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/entrar': typeof EntrarRoute
  '/entrega': typeof EntregaRoute
  '/favoritos': typeof FavoritosRoute
  '/kino': typeof KinoRoute
  '/ofertas': typeof OfertasRoute
  '/parceiros': typeof ParceirosRoute
  '/perfil': typeof PerfilRoute
  '/preferencias': typeof PreferenciasRoute
  '/reservas': typeof ReservasRoute
  '/restaurantes': typeof RestaurantesRoute
  '/sobre': typeof SobreRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/cardapio': typeof AdminCardapioRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/perfil': typeof AdminPerfilRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/admin_/entrar': typeof AdminEntrarRoute
  '/prato/$dishId': typeof PratoDishIdRoute
  '/restaurantes_/$id': typeof RestaurantesIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ajuda'
    | '/cadastro'
    | '/cardapio'
    | '/checkout'
    | '/contacto'
    | '/entrar'
    | '/entrega'
    | '/favoritos'
    | '/kino'
    | '/ofertas'
    | '/parceiros'
    | '/perfil'
    | '/preferencias'
    | '/reservas'
    | '/restaurantes'
    | '/sobre'
    | '/admin/avaliacoes'
    | '/admin/cardapio'
    | '/admin/pedidos'
    | '/admin/perfil'
    | '/admin/reservas'
    | '/admin/entrar'
    | '/prato/$dishId'
    | '/restaurantes/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajuda'
    | '/cadastro'
    | '/cardapio'
    | '/checkout'
    | '/contacto'
    | '/entrar'
    | '/entrega'
    | '/favoritos'
    | '/kino'
    | '/ofertas'
    | '/parceiros'
    | '/perfil'
    | '/preferencias'
    | '/reservas'
    | '/restaurantes'
    | '/sobre'
    | '/admin/avaliacoes'
    | '/admin/cardapio'
    | '/admin/pedidos'
    | '/admin/perfil'
    | '/admin/reservas'
    | '/admin/entrar'
    | '/prato/$dishId'
    | '/restaurantes/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ajuda'
    | '/cadastro'
    | '/cardapio'
    | '/checkout'
    | '/contacto'
    | '/entrar'
    | '/entrega'
    | '/favoritos'
    | '/kino'
    | '/ofertas'
    | '/parceiros'
    | '/perfil'
    | '/preferencias'
    | '/reservas'
    | '/restaurantes'
    | '/sobre'
    | '/admin/avaliacoes'
    | '/admin/cardapio'
    | '/admin/pedidos'
    | '/admin/perfil'
    | '/admin/reservas'
    | '/admin_/entrar'
    | '/prato/$dishId'
    | '/restaurantes_/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AjudaRoute: typeof AjudaRoute
  CadastroRoute: typeof CadastroRoute
  CardapioRoute: typeof CardapioRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactoRoute: typeof ContactoRoute
  EntrarRoute: typeof EntrarRoute
  EntregaRoute: typeof EntregaRoute
  FavoritosRoute: typeof FavoritosRoute
  KinoRoute: typeof KinoRoute
  OfertasRoute: typeof OfertasRoute
  ParceirosRoute: typeof ParceirosRoute
  PerfilRoute: typeof PerfilRoute
  PreferenciasRoute: typeof PreferenciasRoute
  ReservasRoute: typeof ReservasRoute
  RestaurantesRoute: typeof RestaurantesRoute
  SobreRoute: typeof SobreRoute
  AdminEntrarRoute: typeof AdminEntrarRoute
  PratoDishIdRoute: typeof PratoDishIdRoute
  RestaurantesIdRoute: typeof RestaurantesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cardapio': {
      id: '/cardapio'
      path: '/cardapio'
      fullPath: '/cardapio'
      preLoaderRoute: typeof CardapioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrega': {
      id: '/entrega'
      path: '/entrega'
      fullPath: '/entrega'
      preLoaderRoute: typeof EntregaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kino': {
      id: '/kino'
      path: '/kino'
      fullPath: '/kino'
      preLoaderRoute: typeof KinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertas': {
      id: '/ofertas'
      path: '/ofertas'
      fullPath: '/ofertas'
      preLoaderRoute: typeof OfertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceiros': {
      id: '/parceiros'
      path: '/parceiros'
      fullPath: '/parceiros'
      preLoaderRoute: typeof ParceirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferencias': {
      id: '/preferencias'
      path: '/preferencias'
      fullPath: '/preferencias'
      preLoaderRoute: typeof PreferenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservas': {
      id: '/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof ReservasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurantes': {
      id: '/restaurantes'
      path: '/restaurantes'
      fullPath: '/restaurantes'
      preLoaderRoute: typeof RestaurantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/avaliacoes': {
      id: '/admin/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/admin/avaliacoes'
      preLoaderRoute: typeof AdminAvaliacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cardapio': {
      id: '/admin/cardapio'
      path: '/cardapio'
      fullPath: '/admin/cardapio'
      preLoaderRoute: typeof AdminCardapioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/perfil': {
      id: '/admin/perfil'
      path: '/perfil'
      fullPath: '/admin/perfil'
      preLoaderRoute: typeof AdminPerfilRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reservas': {
      id: '/admin/reservas'
      path: '/reservas'
      fullPath: '/admin/reservas'
      preLoaderRoute: typeof AdminReservasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin_/entrar': {
      id: '/admin_/entrar'
      path: '/admin/entrar'
      fullPath: '/admin/entrar'
      preLoaderRoute: typeof AdminEntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prato/$dishId': {
      id: '/prato/$dishId'
      path: '/prato/$dishId'
      fullPath: '/prato/$dishId'
      preLoaderRoute: typeof PratoDishIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurantes_/$id': {
      id: '/restaurantes_/$id'
      path: '/restaurantes/$id'
      fullPath: '/restaurantes/$id'
      preLoaderRoute: typeof RestaurantesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAvaliacoesRoute: typeof AdminAvaliacoesRoute
  AdminCardapioRoute: typeof AdminCardapioRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminPerfilRoute: typeof AdminPerfilRoute
  AdminReservasRoute: typeof AdminReservasRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAvaliacoesRoute: AdminAvaliacoesRoute,
  AdminCardapioRoute: AdminCardapioRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminPerfilRoute: AdminPerfilRoute,
  AdminReservasRoute: AdminReservasRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AjudaRoute: AjudaRoute,
  CadastroRoute: CadastroRoute,
  CardapioRoute: CardapioRoute,
  CheckoutRoute: CheckoutRoute,
  ContactoRoute: ContactoRoute,
  EntrarRoute: EntrarRoute,
  EntregaRoute: EntregaRoute,
  FavoritosRoute: FavoritosRoute,
  KinoRoute: KinoRoute,
  OfertasRoute: OfertasRoute,
  ParceirosRoute: ParceirosRoute,
  PerfilRoute: PerfilRoute,
  PreferenciasRoute: PreferenciasRoute,
  ReservasRoute: ReservasRoute,
  RestaurantesRoute: RestaurantesRoute,
  SobreRoute: SobreRoute,
  AdminEntrarRoute: AdminEntrarRoute,
  PratoDishIdRoute: PratoDishIdRoute,
  RestaurantesIdRoute: RestaurantesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
